# https://book.getfoundry.sh/reference/config/overview

[profile.default]
src = "contracts"
libs = ["lib"]
remappings = [
	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
	'@eth-optimism=lib/optimism/packages/',
]
solc = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1 # https://docs.soliditylang.org/en/latest/internals/optimizer.html#optimizer-parameter-runs

[profile.dist]
test = "contracts" # disables tests
out = "artifacts"
cache = false
